// Shared option lists for selectors

export const countryOptions = [
  { value: 'ZW', label: 'Zimbabwe' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'KE', label: 'Kenya' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'UG', label: 'Uganda' },
  { value: 'ZM', label: 'Zambia' },
  { value: 'MW', label: 'Malawi' },
  { value: 'BW', label: 'Botswana' },
  { value: 'NA', label: 'Namibia' },
  { value: 'MZ', label: 'Mozambique' },
  { value: 'AO', label: 'Angola' },
  { value: 'GH', label: 'Ghana' },
  { value: 'CI', label: "Côte d'Ivoire" },
  { value: 'SN', label: 'Senegal' },
  { value: 'ET', label: 'Ethiopia' },
  { value: 'DZ', label: 'Algeria' },
  { value: 'MA', label: 'Morocco' },
  { value: 'TN', label: 'Tunisia' },
  { value: 'EG', label: 'Egypt' },
  // Global
  { value: 'US', label: 'United States' },
  { value: 'CA', label: 'Canada' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'DE', label: 'Germany' },
  { value: 'FR', label: 'France' },
  { value: 'IT', label: 'Italy' },
  { value: 'ES', label: 'Spain' },
  { value: 'PT', label: 'Portugal' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'SE', label: 'Sweden' },
  { value: 'NO', label: 'Norway' },
  { value: 'FI', label: 'Finland' },
  { value: 'PL', label: 'Poland' },
  { value: 'RU', label: 'Russia' },
  { value: 'TR', label: 'Türkiye' },
  { value: 'AE', label: 'United Arab Emirates' },
  { value: 'SA', label: 'Saudi Arabia' },
  { value: 'IN', label: 'India' },
  { value: 'CN', label: 'China' },
  { value: 'JP', label: 'Japan' },
  { value: 'KR', label: 'South Korea' },
  { value: 'AU', label: 'Australia' },
  { value: 'NZ', label: 'New Zealand' },
  { value: 'BR', label: 'Brazil' },
  { value: 'AR', label: 'Argentina' },
  { value: 'MX', label: 'Mexico' },
];

export const timezoneOptions = [
  { value: 'Africa/Harare', label: 'Africa/Harare (Zimbabwe)' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (South Africa)' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos (Nigeria)' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi (Kenya/EAT)' },
  { value: 'Africa/Cairo', label: 'Africa/Cairo (Egypt/EET)' },
  { value: 'Africa/Casablanca', label: 'Africa/Casablanca (Morocco/WET)' },
  { value: 'Africa/Tunis', label: 'Africa/Tunis (Tunisia/CET)' },
  { value: 'Africa/Maputo', label: 'Africa/Maputo (Mozambique/CAT)' },
  { value: 'Africa/Windhoek', label: 'Africa/Windhoek (Namibia)' },
  { value: 'Africa/Gaborone', label: 'Africa/Gaborone (Botswana)' },
  { value: 'UTC', label: 'UTC' },
  { value: 'Europe/London', label: 'Europe/London (UK)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (France)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (Germany)' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid (Spain)' },
  { value: 'Europe/Rome', label: 'Europe/Rome (Italy)' },
  { value: 'America/New_York', label: 'America/New_York (ET)' },
  { value: 'America/Chicago', label: 'America/Chicago (CT)' },
  { value: 'America/Denver', label: 'America/Denver (MT)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles (PT)' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo (Brazil)' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai (UAE/GST)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata (India/IST)' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore (SGT)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (Japan/JST)' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney (AET)' },
];

export const currencyOptions = [
  { value: 'ZWL', label: 'Zimbabwe Dollar (ZWL)' },
  { value: 'USD', label: 'US Dollar (USD)' },
  { value: 'ZAR', label: 'South African Rand (ZAR)' },
  { value: 'NGN', label: 'Nigerian Naira (NGN)' },
  { value: 'KES', label: 'Kenyan Shilling (KES)' },
  { value: 'TZS', label: 'Tanzanian Shilling (TZS)' },
  { value: 'UGX', label: 'Ugandan Shilling (UGX)' },
  { value: 'GHS', label: 'Ghanaian Cedi (GHS)' },
  { value: 'MWK', label: 'Malawian Kwacha (MWK)' },
  { value: 'MZN', label: 'Mozambican Metical (MZN)' },
  { value: 'AOA', label: 'Angolan Kwanza (AOA)' },
  { value: 'MAD', label: 'Moroccan Dirham (MAD)' },
  { value: 'TND', label: 'Tunisian Dinar (TND)' },
  { value: 'EGP', label: 'Egyptian Pound (EGP)' },
  // Global
  { value: 'EUR', label: 'Euro (EUR)' },
  { value: 'GBP', label: 'British Pound (GBP)' },
  { value: 'CAD', label: 'Canadian Dollar (CAD)' },
  { value: 'AUD', label: 'Australian Dollar (AUD)' },
  { value: 'JPY', label: 'Japanese Yen (JPY)' },
  { value: 'CNY', label: 'Chinese Yuan (CNY)' },
  { value: 'INR', label: 'Indian Rupee (INR)' },
  { value: 'BRL', label: 'Brazilian Real (BRL)' },
  { value: 'MXN', label: 'Mexican Peso (MXN)' },
];


